# -*- coding: utf-8 -*-
"""covid_analysis1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krKCBvS-71soGezkt-gWQjsHUIwvVrBz
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

# =====================================================
# START SPARK
# =====================================================

spark = SparkSession.builder \
    .appName("COVID19 Analysis") \
    .getOrCreate()

# =====================================================
# LOAD DATA
# =====================================================

cases = spark.read.csv(
    "/covid/cases/cases.csv",
    header=True,
    inferSchema=True
)

vax = spark.read.csv(
    "/covid/vaxstatus/vax.csv",
    header=True,
    inferSchema=True
)

age = spark.read.csv(
    "/covid/age/age.csv",
    header=True,
    inferSchema=True
)

# =====================================================
# DATA CLEANING
# =====================================================

cases = cases.na.fill(0)
vax = vax.na.fill(0)
age = age.na.fill(0)

# =====================================================
# 1. STATE-WISE TOTAL CASES
# =====================================================

print("\nSTATE CASES")

state_cases = cases.groupBy("state") \
    .agg(sum("cases_new").alias("total_cases")) \
    .orderBy(desc("total_cases"))

state_cases.show(10)

# =====================================================
# 2. DAILY CASE TREND
# =====================================================

print("\nDAILY TREND")

daily_trend = cases.groupBy("report_date") \
    .agg(sum("cases_new").alias("daily_cases")) \
    .orderBy("report_date")

daily_trend.show(10)

# =====================================================
# 3. RECOVERY ANALYSIS
# =====================================================

print("\nRECOVERY ANALYSIS")

recovery = cases.select(
    "report_date",
    "state",
    "cases_new",
    "cases_recovered",
    "cases_active"
)

recovery.show(10)

# =====================================================
# 4. VACCINATION ANALYSIS
# =====================================================

print("\nVACCINATION ANALYSIS")

vax_summary = vax.groupBy("state").agg(
    sum("cases_unvax").alias("unvax"),
    sum("cases_pvax").alias("pvax"),
    sum("cases_fvax").alias("fvax"),
    sum("cases_boost").alias("boost")
)

vax_summary.show(10)

# =====================================================
# 5. AGE ANALYSIS
# =====================================================

print("\nAGE ANALYSIS")

age_summary = age.agg(
    sum("cases_child").alias("child"),
    sum("cases_adolescent").alias("adolescent"),
    sum("cases_adult").alias("adult"),
    sum("cases_elderly").alias("elderly")
)

age_summary.show()

# =====================================================
# 6. JOIN ALL DATASETS
# =====================================================

print("\nJOINED DATA")

joined = cases.join(
    vax,
    ["report_date", "state"],
    "inner"
).join(
    age,
    ["report_date", "state"],
    "inner"
)

joined.show(10)

# =====================================================
# 7. RISK SCORE
# =====================================================

print("\nRISK SCORE")

risk = joined.groupBy("state").agg(
    sum("cases_new").alias("cases"),
    sum("cases_active").alias("active"),
    sum("cases_unvax").alias("unvax"),
    sum("cases_elderly").alias("elderly")
)

risk = risk.withColumn(
    "risk_score",
    col("cases") * 0.4 +
    col("active") * 0.3 +
    col("unvax") * 0.2 +
    col("elderly") * 0.1
)

risk.orderBy(desc("risk_score")).show(10)

# =====================================================
# SAVE OUTPUTS
# =====================================================

state_cases.write.mode("overwrite") \
    .option("header", True) \
    .csv("/covid/output/state_cases")

daily_trend.write.mode("overwrite") \
    .option("header", True) \
    .csv("/covid/output/daily_trend")

vax_summary.write.mode("overwrite") \
    .option("header", True) \
    .csv("/covid/output/vax_summary")

risk.write.mode("overwrite") \
    .option("header", True) \
    .csv("/covid/output/risk_score")

print("=== ANALYSIS COMPLETED ===")

spark.stop()